CREATE TABLE households (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    display_name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL
);

CREATE TABLE user_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    display_name VARCHAR(100),
    date_of_birth DATE,
    gender VARCHAR(20) NOT NULL,
    age INTEGER NOT NULL,
    height_cm FLOAT(53) NOT NULL,
    starting_weight_kg FLOAT(53) NOT NULL,
    current_weight_kg FLOAT(53) NOT NULL,
    target_weight_kg FLOAT(53) NOT NULL,
    activity_level VARCHAR(30),
    goal_type VARCHAR(30),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT chk_user_profiles_age CHECK (age BETWEEN 1 AND 150)
);

CREATE TABLE user_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(254) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    enabled BOOLEAN NOT NULL,
    household_id BIGINT NOT NULL,
    user_profile_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_user_accounts_email UNIQUE (email),
    CONSTRAINT uk_user_accounts_user_profile UNIQUE (user_profile_id),
    CONSTRAINT fk_user_accounts_household
        FOREIGN KEY (household_id) REFERENCES households (id),
    CONSTRAINT fk_user_accounts_user_profile
        FOREIGN KEY (user_profile_id) REFERENCES user_profiles (id)
);

CREATE TABLE health_metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_profile_id BIGINT NOT NULL,
    metric_date DATE NOT NULL,
    weight_kg NUMERIC(6, 2) NOT NULL,
    notes VARCHAR(500),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_health_metrics_user_profile_metric_date
        UNIQUE (user_profile_id, metric_date),
    CONSTRAINT fk_health_metrics_user_profile
        FOREIGN KEY (user_profile_id) REFERENCES user_profiles (id)
);

CREATE TABLE food_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_profile_id BIGINT NOT NULL,
    entry_date DATE NOT NULL,
    meal_type VARCHAR(20) NOT NULL,
    food_name VARCHAR(150) NOT NULL,
    quantity NUMERIC(10, 2) NOT NULL,
    unit VARCHAR(50) NOT NULL,
    calories NUMERIC(10, 2) NOT NULL,
    protein_g NUMERIC(10, 2) NOT NULL,
    carbohydrates_g NUMERIC(10, 2) NOT NULL,
    fat_g NUMERIC(10, 2) NOT NULL,
    notes VARCHAR(500),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_food_entries_user_profile
        FOREIGN KEY (user_profile_id) REFERENCES user_profiles (id)
);

CREATE TABLE water_goals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_profile_id BIGINT NOT NULL,
    daily_goal_ml INTEGER NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_water_goals_user_profile UNIQUE (user_profile_id),
    CONSTRAINT fk_water_goals_user_profile
        FOREIGN KEY (user_profile_id) REFERENCES user_profiles (id)
);

CREATE TABLE water_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_profile_id BIGINT NOT NULL,
    entry_date DATE NOT NULL,
    amount_ml INTEGER NOT NULL,
    notes VARCHAR(500),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_water_entries_user_profile
        FOREIGN KEY (user_profile_id) REFERENCES user_profiles (id)
);

CREATE TABLE activity_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_profile_id BIGINT NOT NULL,
    activity_date DATE NOT NULL,
    category VARCHAR(30) NOT NULL,
    activity_name VARCHAR(100) NOT NULL,
    duration_minutes INTEGER NOT NULL,
    steps INTEGER,
    distance_km NUMERIC(10, 3),
    reported_calories_burned INTEGER,
    notes VARCHAR(500),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT chk_activity_entries_duration CHECK (duration_minutes <= 1440),
    CONSTRAINT chk_activity_entries_steps CHECK (steps BETWEEN 0 AND 1000000),
    CONSTRAINT chk_activity_entries_reported_calories
        CHECK (reported_calories_burned BETWEEN 0 AND 100000),
    CONSTRAINT fk_activity_entries_user_profile
        FOREIGN KEY (user_profile_id) REFERENCES user_profiles (id)
);

CREATE TABLE sleep_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_profile_id BIGINT NOT NULL,
    sleep_date DATE NOT NULL,
    sleep_type VARCHAR(20) NOT NULL,
    start_date_time TIMESTAMP(6) NOT NULL,
    end_date_time TIMESTAMP(6) NOT NULL,
    quality_rating INTEGER,
    notes VARCHAR(500),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT chk_sleep_entries_quality CHECK (quality_rating BETWEEN 1 AND 5),
    CONSTRAINT fk_sleep_entries_user_profile
        FOREIGN KEY (user_profile_id) REFERENCES user_profiles (id)
);

CREATE TABLE goals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_profile_id BIGINT NOT NULL,
    title VARCHAR(100) NOT NULL,
    goal_type VARCHAR(30) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    target_value BIGINT NOT NULL,
    qualifying_sleep_minutes INTEGER,
    custom_unit VARCHAR(30),
    status VARCHAR(20) NOT NULL,
    notes VARCHAR(500),
    completed_at TIMESTAMP(6),
    cancelled_at TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT chk_goals_qualifying_sleep
        CHECK (qualifying_sleep_minutes <= 1440),
    CONSTRAINT fk_goals_user_profile
        FOREIGN KEY (user_profile_id) REFERENCES user_profiles (id)
);

CREATE TABLE goal_check_ins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    goal_id BIGINT NOT NULL,
    check_in_date DATE NOT NULL,
    completed BOOLEAN NOT NULL,
    notes VARCHAR(500),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_goal_check_ins_goal_date UNIQUE (goal_id, check_in_date),
    CONSTRAINT fk_goal_check_ins_goal
        FOREIGN KEY (goal_id) REFERENCES goals (id)
);

CREATE TABLE couple_challenges (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    challenge_type VARCHAR(30) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    target_value BIGINT NOT NULL,
    qualifying_sleep_minutes INTEGER,
    custom_unit VARCHAR(30),
    status VARCHAR(20) NOT NULL,
    notes VARCHAR(500),
    completed_at TIMESTAMP(6),
    cancelled_at TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT chk_couple_challenges_qualifying_sleep
        CHECK (qualifying_sleep_minutes <= 1440)
);

CREATE TABLE couple_challenge_participants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    couple_challenge_id BIGINT NOT NULL,
    user_profile_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_couple_challenge_participants_challenge_profile
        UNIQUE (couple_challenge_id, user_profile_id),
    CONSTRAINT fk_couple_challenge_participants_challenge
        FOREIGN KEY (couple_challenge_id) REFERENCES couple_challenges (id),
    CONSTRAINT fk_couple_challenge_participants_user_profile
        FOREIGN KEY (user_profile_id) REFERENCES user_profiles (id)
);

CREATE TABLE challenge_check_ins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    participant_id BIGINT NOT NULL,
    check_in_date DATE NOT NULL,
    completed BOOLEAN NOT NULL,
    notes VARCHAR(500),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_challenge_check_ins_participant_date
        UNIQUE (participant_id, check_in_date),
    CONSTRAINT fk_challenge_check_ins_participant
        FOREIGN KEY (participant_id) REFERENCES couple_challenge_participants (id)
);
