CREATE TABLE partner_invitations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    household_id BIGINT NOT NULL,
    inviter_account_id BIGINT NOT NULL,
    invite_code_hash VARCHAR(64) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    expires_at TIMESTAMP(6) NOT NULL,
    accepted_at TIMESTAMP(6),
    revoked_at TIMESTAMP(6),
    CONSTRAINT uk_partner_invitations_invite_code_hash UNIQUE (invite_code_hash),
    CONSTRAINT fk_partner_invitations_household
        FOREIGN KEY (household_id) REFERENCES households (id),
    CONSTRAINT fk_partner_invitations_inviter_account
        FOREIGN KEY (inviter_account_id) REFERENCES user_accounts (id)
);

CREATE INDEX idx_partner_invitations_household
    ON partner_invitations (household_id);
